version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: carddeck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: ./api
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: carddeck
      JWT_SECRET: something-secret
    ports:
      - "3001:3001"
    depends_on:
      - db

  ui:
    build: ./ui
    ports:
      - "5173:5174"
    environment:
      VITE_API_URL: http://localhost:3001
    depends_on:
      - api

volumes:
  dbdata: